= Reference Manual
:page-date: 2019-03-29 00:00:00 Z
:page-last_modified_at: 2024-12-01 00:00:00 Z

Tackler configuration is controlled by configuration files and command line options.

== Reference configuration and examples


* Main tackler configuration file: xref:reference:tackler-toml.adoc[tackler.toml]
* Account names: xref:reference:accounts-toml.adoc[accounts.toml]
* Commodity names: xref:reference:accounts-toml.adoc[accounts.toml]
* Transaction Tag names: xref:reference:tags-toml.adoc[tags.toml]
* Examples for production systems: :example:production-setups.adoc[Example Setups]


== Configuration discovery

Path to the tackler configuration file is mandatory option.
The philosophy of the configuration is "what you see is what you get",
e.g. there aren't any internal defaults for configuration.

=== Merging configurations to active set

Tackler will create an active configuration in following way:

* Provided configuration will be the baseline
* Cmd-line arguments will override the provided configuration
