= Installation Manual
:page-date: 2019-03-29 00:00:00 Z
:page-last_modified_at: 2025-01-21 00:00:00 Z

This is installation manual for tackler command line.

To use tackler cli you will need

  * Tackler command line binary
  * Valid configuration file (xref:reference:tackler-toml.adoc[tackler.toml])

To build the tackler binary, you need to have link:https://www.rust-lang.org/tools/install[Rust toolchain installed].


== Build and install with Cargo

[source,bash]
----
cargo install tackler
----

It will make the tackler command globally available, if you've allowed link:https://www.rust-lang.org/tools/install[Rust toolchain installation] to modify your PATH. If not, the binary is located at `CARGO_HOME/bin`, that's typically `~/.cargo/bin/tackler` on MacOS and Linux, and `C:\Users\<UserName>\.cargo\bin` on Windows.

You can uninstall tackler by running  `cargo uninstall tackler`.

== Build from source

[source,bash]
----
# Get the source code
git clone --recurse-submodules https://github.com/tackler-ng/tackler

cd tackler

# Check the releases
git tag -l

# Select the latest release, e.g. v25.01.1
git checkout v25.01.1

# Build the tackler
cargo build --release --locked --bin tackler

# Check the version info
target/release/tackler --version

tackler 25.1.1 (v25.01.1 - e730633c1ba23e6)
----


== Minimal setup

Minimal initial installation and setup is described in xref:ROOT:quickstart.adoc[Quickstart Guide].

Tackler could be used with minimal quickstart setup just fine, but to get most out of it (strict modes, git storage system, Audit trail functinality etc.), it must be configured properly. Below is recommended setup for production use.


[[layout]]
== Recommended Setup and layout

You can create default journal setup with `tackler new journal` command. This will create a new journal setup with default configuration files and example transactions, as laid out below:

Full setup would be:

----
.
├── bin
│   └── tackler
└── journal
    ├── conf
    │   ├── tackler.toml
    │   ├── accounts.toml
    │   ├── commodities.toml
    │   └── tags.toml
    └── txns
        ├── ...
        ├── 2020
        │   ├── ...
        │   └── 12
        │       ├── journal-1.txn
        │       └── journal-2.txn
        └── 2021
            └── 01
                ├── journal-1.txn
                └── journal-2.txn
----

This setup uses year/month based sharding for transactions (the directory structure under `txns`).  It's up to for each
system to decide which is xref:journal:sharding.adoc[the best way to shard transaction data], or not to shard transactions at all.


=== Configuration Settings for Recommended Layout

Provide path to configuration with `--config` option.

==== tackler.toml

The tackler main configuration is file located under conf:

.journal/conf/tackler.toml
[source, toml]
----
[kernel.input]
storage = "fs"
fs  = { path = "..",      dir = "txns", suffix = "txn" }
git = { repo = "../.git", dir = "txns", suffix = "txn", ref = "main" }
...
[transaction]
accounts    = { path = "accounts.toml" }
commodities = { path = "commodities.toml" }
tags        = { path = "tags.toml" }
----

This setup makes it possible to separate journal setup and data, and store relevant configuration next to transaction data (and possibly under version control).

See :example:production-setups.adoc#backend-fs-or-git[Configuration Example: fs or git] how combine git based transaction storage with this setup.


==== accounts.toml

If there is missing or mistyped account, that will cause an error and tackler will stop processing journal.
See xref:reference:accounts-toml.adoc[accounts.toml] for full documentation
of Chart of Accounts and commodity listing.

==== commodities.toml

If there is missing or mistyped commodities, that will cause an error
and tackler will stop processing journal.
See xref:reference:commodities-toml.adoc[commodities.toml] for full
documentation  of Chart of Accounts and commodity listing.


==== tags.toml

If there is missing or mistyped tag, that will cause an error and tackler will stop processing journal.
See xref:reference:tags-toml.adoc[tags.toml] for full documentation
of Chart of Tags.

== Next steps

See reference configuration files for full details:

* xref:reference:tackler-toml.adoc[tackler.toml]
* xref:reference:accounts-toml.adoc[accounts.toml]
* xref:reference:commodities-toml.adoc[commodities.toml]
* xref:reference:tags-toml.adoc[tags.toml]

xref:journal:git-storage.adoc[Git Storage Guide] has information how to use integrated version control features with Tackler.

Git and filesystem based production setup is described in :example:production-setups.adoc#backend-fs-or-git[Configuration Example]

xref:journal:sharding.adoc[Transaction Data Sharding] has ideas for different storage schemes.
