= Reliability
:page-date: 2019-03-29 00:00:00 Z
:page-last_modified_at: 2025-03-31 00:00:00 Z

[quote]
____
Simplicity is prerequisite for reliability +
as reliability is for integrity +
when integrity is the essence of trust.
____

Tackler's operations and results must always be correct and trustworthy. If there are any errors with journal,
then it will fail fast and hard and won't process dubious input as valid one.

== Performance

Tackler has excellent performance characteristics - it can process more than 700_000 txns per second
on modern laptop. See xref:ROOT:features/performance.adoc[Performance Overview] for details.


== Testing

Foundation of tackler development is that all features must be tested logically and code-wise,
and overall test coverage should be almost perfect.  Tackler is tested with functional and
logical test sets to ensure that all code paths are covered by tests.

Tackler has *115* tracked features.
These features are verified by *495* tracked test cases.
Tackler-ng is currently tested with *422* tests vectors,
and test results are verified by *481* reference reports.

Part of the test setup is journal with
{github-link}/tackler-core/tests/git_txns.rs#L103[*one hundred thousand* (100 000)] transactions.
It is processed several times in a loop to verify tackler's ability handle repeatably journals with many transactions.

Tackler is stress and performance tested with up to {github-link}/perf/index.adoc[*one million* (1E6)]
transactions sets with external test setup.

=== Tackler Test Tracking Database

{github-link}/suite/tests.adoc[Tackler Test Tracking Database (T3DB)] tracks features
and tests for those features. T3DB is used to ensure that all features 
and error paths for those features are tested, that test setup has as little as 
possible of overlapping tests and prevent  duplicate test cases.

T3DB also provides reverse mapping from a test case back to the feature,
which is validated by that test case.
