= Equity export
:page-date: 2019-03-29 00:00:00 Z
:page-last_modified_at: 2024-12-01 00:00:00 Z

Equity export produces a transaction which records
current state of accounts.

== Equity export configuration


See xref:reference:tackler-toml.adoc[tackler.toml] and `export.equity.*`
for full information of equity export configuration options.

=== Account filtering

Accounts for Equity report can be filtered with cli option `--accounts`,
global `report.accounts`  or export specific `export.equity.accounts`
setting.

== Commodity Price conversion

If Commodity conversion is activated (see
xref:tackler:commodities:price/index.adoc[]), then equity transaction is
generated with price data based on that. To disable this behaviour, disable
price conversion with `--price.lookup-type none`.

== Metadata

Transaction timestamp is same as timestamp of the last transaction
which was used to calculate equity.

If the last transaction had an uuid, then it is recorded into equity's
metadata section.

....
2016-11-25T09:36:00+00:00 'Equity txn
   ; Last txn (uuid) : 9e902481-1609-5f1a-9640-c3d40b6b66f9
   ;
...
....

== Example export

This is full equity export, run with the Tackler's audit example:

----
tackler \
   --config examples/audit.toml \
   --output.dir .\
   --output.prefix audit \
   --exports equity \
   --reports ""
----

....
2016-11-25T09:36:00+00:00 'Equity txn
   ; Last txn (uuid) : 9e902481-1609-5f1a-9640-c3d40b6b66f9
   ;
   ; Git Storage
   ;       reference : set-1e1
   ;       directory : txns
   ;       extension : txn
   ;          commit : ed6e4b10de2daea8d143569c473d14a9b09c3270
   ;          author : tackler <accounting@example.com>
   ;            date : 2016-11-25 09:36:00 +0000
   ;         subject : set-1e1: 2016-11-25
   ;
   ; Txn Set Checksum
   ;         SHA-256 : 4a0eb2f8836447a025030a87136c047b4a737031162f593cb00f390c6ba113a3
   ;        set size : 10
   ;
   ; Account Selector Checksum
   ;         SHA-256 : df4714ff3f5bd031a8256df95863a8085f740b436f1b47febb45c9eb9aaa9e9e
   ;        selector : 'a:.*'
   ;
   a:ay2016:am01  -1.0000001
   a:ay2016:am02  -6.0000001
   a:ay2016:am03  -14.0000001
   a:ay2016:am04  -19.0000001
   a:ay2016:am05  -26.0000001
   a:ay2016:am07  -2.0000001
   a:ay2016:am08  -7.0000001
   a:ay2016:am09  -13.0000001
   a:ay2016:am10  -19.0000001
   a:ay2016:am11  -25.0000001
   Equity:Balance  132.0000010
....
